name: efarm
description: A platform in which user can upload his ad related to category of animals and can contact seller

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  firebase_auth: ^0.20.1
  firebase_core: any
  cloud_firestore: any
  sms_autofill: ^1.3.1
  font_awesome_flutter: any


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/background/sheep.jpg
    - assets/icons/

  fonts:
    - family: JameelNooriNastalerq
      fonts:
        - asset: assets/font/jameel_noori_nastaleeq.ttf